print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
heigth = input()
print("How much so you weight?", end=' ')
weight = input()
print(f"So, you're {age} old, {heigth} tall and {weight} heavy.")
